application:
  name: timekeeper
  project: TimeKeeperQuarkus
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "10.10"
  name: my-postgresql-6132005
routers:
- name: main
  routes:
  - application_name: timekeeper
    paths:
    - /*
